//
// Copyright (c) .NET Foundation and Contributors
// See LICENSE file in the project root for full license information.
//

//////////////////////////////////////////////////////////////////////////////
// This file was automatically generated by a tool.                         //
// Any changes you make here will be overwritten when it's generated again. //
//////////////////////////////////////////////////////////////////////////////

#ifndef _TARGET_BOARD_NANOBOOTER_H_
#define _TARGET_BOARD_NANOBOOTER_H_

#include <target_common.h>

#define OEMSYSTEMINFOSTRING "nanoCLR running RaspberryPiPico-DK"

#define NANOCLR_AUDIO FALSE
#define NANOCLR_ETHERNET FALSE
#define NANOCLR_FDCAN FALSE
#define NANOCLR_GRAPHICS TRUE
#define NANOCLR_GRAPHICS_USING_SPI FALSE
#define NANOCLR_MICROSD FALSE
#define NANOCLR_RTC FALSE
#define NANOCLR_USB FALSE

#define __NOP() 

#endif /* _TARGET_BOARD_NANOBOOTER_H_ */
