name: Devcontainer build for FreeRTOS targets # NOTE: we currently build against "All", since there is no optimized container.

on: # FreeRTOS specific changes. We specifically ignore other (RTOS) target changes.
  push:
    paths:
      - '!**/*.md'
      - '.github/workflows/build-freertos-nxp-targets.yml'
      - '.devcontainer/sources/Dockerfile.FreeRTOS.NXP'
      - '.devcontainer/Dockerfile.FreeRTOS.NXP'
      - '.devcontainer/devcontainer.json'
      - 'targets/FreeRTOS/**'
      - 'targets-community/FreeRTOS/**'
      - 'src/**'
      - 'CMake/**'
      - 'bootloader_components/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
  pull_request:
    paths:
      - '!**/*.md'
      - '.github/workflows/build-freertos-nxp-targets.yml'
      - '.devcontainer/sources/Dockerfile.FreeRTOS.NXP'
      - '.devcontainer/Dockerfile.FreeRTOS.NXP'
      - '.devcontainer/devcontainer.json'
      - 'targets/FreeRTOS/**'
      - 'targets-community/FreeRTOS/**'
      - 'src/**'
      - 'CMake/**'
      - 'bootloader_components/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
  release:
    types:
      - created
  workflow_dispatch:


jobs:
  build-target:
    strategy:
      fail-fast: false # Continues to build other targets in the matrix, even if one fails.

      matrix: # Add the target and build type you wish to generate firmware for:
        include: [
          { target: NXP_MIMXRT1060_EVK, build-type: MinSizeRel },
          { target: NXP_MIMXRT1060_EVK, build-type: Debug },


          # Community targets:

        ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update repo submodules
        run: |
          git submodule update --init

      - name: Adjust config templates for devcontainer
        run: |
            # Move into the config directory
            pushd config
            
            # Rename the templates
            mv user-prefs.TEMPLATE.json user-prefs.json
            mv user-tools-repos.TEMPLATE.json user-tools-repos.json
           
            # Adjust the file content for a devcontainer
            sed -i -- 's|"name": "user-tools-repos-container"|"name": "user-tools-repos"|g' user-tools-repos.json
            
            # Move out of the config directory
            popd

      - name: Adjust devcontainer.json (FreeRTOS)
        run: |
            # Move into the .devcontainer directory
            pushd .devcontainer

            # fix if needed.
            sed -i -- 's|"dockerFile": "Dockerfile.All"|"dockerFile": "./sources/Dockerfile.FreeRTOS.NXP"|g' devcontainer.json

            # Move out of the .devcontainer directory
            popd

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.target }} ${{ matrix.build-type }} Firmware
        uses: devcontainers/ci@v0.3
        with:
          # The FreeRTOS container
          # cacheFrom: sources/Dockerfile.FreeRTOS.NXP # ubuntu:latest # ghcr.io/nanoframework/dev-container-freertos
          push: never
          runCmd: |
            # Build target:
            cmake --preset=${{ matrix.target }} -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
            cmake --build build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Firmware ${{ matrix.target }}-${{ matrix.build-type }}
          path: |
            ./build/*.map
            ./build/*.elf
            ./build/*.hex
            ./build/*.bin
            ./build/*.dfu
